/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.Color;
import java.awt.Point;
import sm.aadcg.iu.Lienzo2DImagen;

/**
 *
 * @author alberto
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    private VentanaPrincipal parent;
    private int _imgx = 300;
    private int _imgy = 300;
    
    public VentanaInterna(VentanaPrincipal parent) {
        this.parent = parent;
        initComponents();
        this.setResizable(true);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
        
    }
    
    public void set_imgx (int imgx) {
        this._imgx = imgx;
    }
    public int get_imgx () {
        return this._imgx;
    }
    public void set_imgy (int imgy) {
        this._imgy = imgy;
    }
    public int get_imgy () {
        return this._imgy;
    }
    /**
     * Creates new form VentanaInterna
     */
    /*public VentanaInterna() {
        initComponents();
        this.setResizable(true);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2DImagen2 = new sm.aadcg.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setMinimumSize(new java.awt.Dimension(300, 300));
        setPreferredSize(new java.awt.Dimension(300, 300));
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        lienzo2DImagen2.setMaximumSize(new java.awt.Dimension(2147483647, 2147483647));
        lienzo2DImagen2.setLayout(new java.awt.BorderLayout());
        jScrollPane1.setViewportView(lienzo2DImagen2);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        System.out.println("X: " + evt.getX() + " Y: " + evt.getY());
        this.parent.set_jlabel2(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseMoved

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this.parent.set_lienzo_atributos(this.getLienzo().get_modo_dibujo(),
                this.getLienzo().get_color(), this.getLienzo().get_transparencia(),
                this.getLienzo().get_fill(), this.getLienzo().get_grosor(), 
                this.getLienzo().get_alisar());
    }//GEN-LAST:event_formInternalFrameActivated

    public Lienzo2DImagen getLienzo() {
        return this.lienzo2DImagen2;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.aadcg.iu.Lienzo2DImagen lienzo2DImagen2;
    // End of variables declaration//GEN-END:variables
}
