/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica4;

import java.awt.Color;
import java.io.File;
import javax.swing.JFileChooser;

/**
 *
 * @author alberto
 */
public class VentanaPrincipal extends javax.swing.JFrame {
    
    
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new java.awt.Panel();
        panel2 = new java.awt.Panel();
        jToolBar1 = new javax.swing.JToolBar();
        jToggleButton5 = new javax.swing.JToggleButton();
        jToggleButton6 = new javax.swing.JToggleButton();
        jToggleButton7 = new javax.swing.JToggleButton();
        jToggleButton8 = new javax.swing.JToggleButton();
        panel5 = new java.awt.Panel();
        panel6 = new java.awt.Panel();
        jTextPane1 = new javax.swing.JTextPane();
        panel1 = new java.awt.Panel();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jCheckBox1 = new javax.swing.JCheckBox();
        lienzo2 = new practica4.Lienzo();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        new_file = new javax.swing.JMenuItem();
        open_file = new javax.swing.JMenuItem();
        save_file = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        state_bar = new javax.swing.JCheckBoxMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel3.setLayout(new java.awt.BorderLayout());

        jToolBar1.setRollover(true);

        jToggleButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/drawing.png"))); // NOI18N
        jToggleButton5.setFocusable(false);
        jToggleButton5.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton5.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton5MouseClicked(evt);
            }
        });
        jToolBar1.add(jToggleButton5);

        jToggleButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/line.png"))); // NOI18N
        jToggleButton6.setFocusable(false);
        jToggleButton6.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton6.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton6.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseDragged(evt);
            }
        });
        jToggleButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton6MouseClicked(evt);
            }
        });
        jToolBar1.add(jToggleButton6);

        jToggleButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/photo-frame.png"))); // NOI18N
        jToggleButton7.setFocusable(false);
        jToggleButton7.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton7.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton7MouseClicked(evt);
            }
        });
        jToolBar1.add(jToggleButton7);

        jToggleButton8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/ellipse-outline-shape-variant.png"))); // NOI18N
        jToggleButton8.setFocusable(false);
        jToggleButton8.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton8.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jToggleButton8MouseClicked(evt);
            }
        });
        jToolBar1.add(jToggleButton8);

        panel2.add(jToolBar1);

        panel3.add(panel2, java.awt.BorderLayout.WEST);

        getContentPane().add(panel3, java.awt.BorderLayout.PAGE_START);

        panel5.setLayout(new java.awt.BorderLayout());

        panel6.setBackground(new java.awt.Color(238, 238, 238));
        panel6.setLayout(new java.awt.BorderLayout());

        jTextPane1.setBackground(new java.awt.Color(223, 223, 223));
        jTextPane1.setBorder(null);
        jTextPane1.setText("a");
        panel6.add(jTextPane1, java.awt.BorderLayout.SOUTH);

        panel1.setLayout(new java.awt.GridLayout(2, 3));

        jButton3.setBackground(new java.awt.Color(238, 238, 238));
        jButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rblackcircle.png"))); // NOI18N
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        panel1.add(jButton3);

        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rredcircle.png"))); // NOI18N
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });
        panel1.add(jButton5);

        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rbluecircle.png"))); // NOI18N
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        panel1.add(jButton2);

        jButton1.setBackground(new java.awt.Color(205, 205, 205));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rwhitecircle.png"))); // NOI18N
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        panel1.add(jButton1);

        jButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/ryellowcircle.png"))); // NOI18N
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });
        panel1.add(jButton4);

        jButton6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/practica4/rgreencircle.png"))); // NOI18N
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        panel1.add(jButton6);

        panel6.add(panel1, java.awt.BorderLayout.WEST);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jCheckBox1.setBackground(new java.awt.Color(238, 238, 238));
        jCheckBox1.setText("Relleno");
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jCheckBox1, java.awt.BorderLayout.CENTER);

        panel6.add(jPanel1, java.awt.BorderLayout.EAST);

        panel5.add(panel6, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout lienzo2Layout = new javax.swing.GroupLayout(lienzo2);
        lienzo2.setLayout(lienzo2Layout);
        lienzo2Layout.setHorizontalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 722, Short.MAX_VALUE)
        );
        lienzo2Layout.setVerticalGroup(
            lienzo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 338, Short.MAX_VALUE)
        );

        panel5.add(lienzo2, java.awt.BorderLayout.CENTER);

        getContentPane().add(panel5, java.awt.BorderLayout.CENTER);

        jMenu1.setText("Archivo");

        new_file.setText("Nuevo");
        new_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                new_fileActionPerformed(evt);
            }
        });
        jMenu1.add(new_file);

        open_file.setText("Abrir");
        open_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                open_fileActionPerformed(evt);
            }
        });
        jMenu1.add(open_file);

        save_file.setText("Guardar");
        save_file.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                save_fileActionPerformed(evt);
            }
        });
        jMenu1.add(save_file);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edición");

        state_bar.setSelected(true);
        state_bar.setText("Ver barra de estado ");
        state_bar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                state_barActionPerformed(evt);
            }
        });
        jMenu2.add(state_bar);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void open_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_open_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if ( resp == JFileChooser.APPROVE_OPTION ) {
            File f = dlg.getSelectedFile();
            // Code
        }
    }//GEN-LAST:event_open_fileActionPerformed

    private void save_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_save_fileActionPerformed
        // TODO add your handling code here:
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if ( resp == JFileChooser.APPROVE_OPTION ) {
            File f = dlg.getSelectedFile();
            // Codes
        }
    }//GEN-LAST:event_save_fileActionPerformed

    private void new_fileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_new_fileActionPerformed
        // TODO add your handling code here:
        // this.lienzo2.removeAll();
        // this.lienzo2.validate();
        this.lienzo2.reset_points();
        this.lienzo2.repaint();
    }//GEN-LAST:event_new_fileActionPerformed

    private void state_barActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_state_barActionPerformed
        // TODO add your handling code here:
        if (state_bar.isSelected()){
            jTextPane1.setVisible(true);
        } else {
            jTextPane1.setVisible(false);
        }
    }//GEN-LAST:event_state_barActionPerformed

    private void jToggleButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton5MouseClicked
        // TODO add your handling code here:
        if (this.jToggleButton5.isSelected()){
            this.lienzo2.set_draw_mode("point");
            this.jToggleButton6.setSelected(false);
            this.jToggleButton7.setSelected(false);
            this.jToggleButton8.setSelected(false);
        } else {
            this.lienzo2.set_draw_mode(null);
        }
    }//GEN-LAST:event_jToggleButton5MouseClicked

    private void jToggleButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseClicked
        // TODO add your handling code here:
        if (this.jToggleButton6.isSelected()){
            this.lienzo2.set_draw_mode("line");
            this.jToggleButton5.setSelected(false);
            this.jToggleButton7.setSelected(false);
            this.jToggleButton8.setSelected(false);
        } else {
            this.lienzo2.set_draw_mode(null);
        }
    }//GEN-LAST:event_jToggleButton6MouseClicked

    private void jToggleButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton7MouseClicked
        // TODO add your handling code here:
        if (this.jToggleButton7.isSelected()){
            this.lienzo2.set_draw_mode("rectangle");
            this.jToggleButton6.setSelected(false);
            this.jToggleButton5.setSelected(false);
            this.jToggleButton8.setSelected(false);
        } else {
            this.lienzo2.set_draw_mode(null);
        }
    }//GEN-LAST:event_jToggleButton7MouseClicked

    private void jToggleButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton8MouseClicked
        // TODO add your handling code here:
        if (this.jToggleButton8.isSelected()){
            this.lienzo2.set_draw_mode("elipse");
            this.jToggleButton6.setSelected(false);
            this.jToggleButton7.setSelected(false);
            this.jToggleButton5.setSelected(false);
        } else {
            this.lienzo2.set_draw_mode(null);
        }
    }//GEN-LAST:event_jToggleButton8MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.BLACK);
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.RED);
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.BLUE);
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.WHITE);
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.YELLOW);
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:
        this.lienzo2.set_color(Color.GREEN);
    }//GEN-LAST:event_jButton6MouseClicked

    private void jToggleButton6MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jToggleButton6MouseDragged
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jToggleButton6MouseDragged

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
        if (this.jCheckBox1.isSelected()) {
            this.lienzo2.set_fill_color(true);
        } else {
            this.lienzo2.set_fill_color(false);
        }
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextPane jTextPane1;
    private javax.swing.JToggleButton jToggleButton5;
    private javax.swing.JToggleButton jToggleButton6;
    private javax.swing.JToggleButton jToggleButton7;
    private javax.swing.JToggleButton jToggleButton8;
    private javax.swing.JToolBar jToolBar1;
    private practica4.Lienzo lienzo2;
    private javax.swing.JMenuItem new_file;
    private javax.swing.JMenuItem open_file;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private java.awt.Panel panel3;
    private java.awt.Panel panel5;
    private java.awt.Panel panel6;
    private javax.swing.JMenuItem save_file;
    private javax.swing.JCheckBoxMenuItem state_bar;
    // End of variables declaration//GEN-END:variables
}
