/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import com.github.sarxos.webcam.WebcamPanel;
import com.github.sarxos.webcam.Webcam;
import org.slf4j.*;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.image.BufferedImage;

/**
 *
 * @author alberto
 */
public class VentanaInternaWebCam extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInternaWebCam
     */
    private Webcam camera = null;    
    private VentanaPrincipal _parent = null;
    
    private VentanaInternaWebCam(VentanaPrincipal parent) {
        camera = Webcam.getDefault();
        if(camera != null) {
            Dimension resolucion[] = camera.getViewSizes();
            Dimension maxRes = resolucion[resolucion.length-1];
            this.camera.setViewSize(maxRes);
            WebcamPanel areaVisual = new WebcamPanel(camera);
            if(areaVisual!=null) {
                getContentPane().add(areaVisual,BorderLayout.CENTER);
                pack();
            }
            this._parent = parent;
        }
        initComponents();
    }
    
    public static VentanaInternaWebCam getInstance(VentanaPrincipal parent) {
        VentanaInternaWebCam v = new VentanaInternaWebCam(parent);
        return (v.camera!=null?v:null);
    }
    
    public void close() {
        this.camera.close();
    }
    
    public Webcam getCamera(){
        return this.camera;
    }
    
    public BufferedImage capture() {
        BufferedImage img = this.camera.getImage();
        return img;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameClosing(evt);
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameClosing(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameClosing
        // TODO add your handling code here:
        this.close();
    }//GEN-LAST:event_formInternalFrameClosing

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        this._parent.set_jlabel2(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
