/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import sm.aadcg.iu.Lienzo2DImagen;

/**
 *
 * @author alberto
 */
public class VentanaInternaImage extends javax.swing.JInternalFrame {

    private VentanaPrincipal _parent;
    private int _imgx = 300;
    private int _imgy = 300;
    
    
    public VentanaInternaImage(VentanaPrincipal parent) {
        this._parent = parent;
        initComponents();
        this.setResizable(true);
        this.setClosable(true);
        this.setIconifiable(true);
        this.setMaximizable(true);
    }

    public void set_imgx (int imgx) {
        this._imgx = imgx;
    }
    public int get_imgx () {
        return this._imgx;
    }
    public void set_imgy (int imgy) {
        this._imgy = imgy;
    }
    public int get_imgy () {
        return this._imgy;
    }
    
    

    public Lienzo2DImagen getLienzo() {
        return this.lienzo2DImagen1;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        lienzo2DImagen1 = new sm.aadcg.iu.Lienzo2DImagen();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);
        addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                formMouseMoved(evt);
            }
        });
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameActivated(evt);
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
        });

        javax.swing.GroupLayout lienzo2DImagen1Layout = new javax.swing.GroupLayout(lienzo2DImagen1);
        lienzo2DImagen1.setLayout(lienzo2DImagen1Layout);
        lienzo2DImagen1Layout.setHorizontalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        lienzo2DImagen1Layout.setVerticalGroup(
            lienzo2DImagen1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 317, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(lienzo2DImagen1);

        getContentPane().add(jScrollPane1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formInternalFrameActivated(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameActivated
        // TODO add your handling code here:
        this._parent.set_lienzo_atributos(this.getLienzo().get_modo_dibujo(),
                this.getLienzo().get_color_trace(), this.getLienzo().get_transparencia(),
                this.getLienzo().get_fill(), this.getLienzo().get_grosor(), 
                this.getLienzo().get_alisar(), this.getLienzo().get_editar(),
                this.getLienzo().get_color_fill(), this.getLienzo().get_mode_stroke());
        //PROVISIONAL
        // this.getLienzo()
    }//GEN-LAST:event_formInternalFrameActivated

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        this._parent.set_jlabel2(evt.getX(), evt.getY());
    }//GEN-LAST:event_formMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private sm.aadcg.iu.Lienzo2DImagen lienzo2DImagen1;
    // End of variables declaration//GEN-END:variables
}
